CREATE TABLE [dbo].[Category] (
    [CategoryID]  INT            IDENTITY (1, 1) NOT NULL,
    [Category2ID] INT            NULL,
    [Name]        NVARCHAR (MAX) NULL,
    [Col1]        BIT            NULL,
    [Col2]        BIT            NULL,
    [Col3]        BIT            NULL,
    [Col4]        BIT            NULL,
    [Col5]        BIT            NULL,
    [Col6]        BIT            NULL,
    [Col7]        BIT            NULL,
    [Col8]        BIT            NULL,
    [Col9]        BIT            NULL,
    [Col10]       BIT            NULL,
    [Col11]       BIT            NULL,
    [Col12]       BIT            NULL,
    [Col13]       BIT            NULL,
    [Col14]       BIT            NULL,
    [Col15]       BIT            NULL,
    [Col16]       BIT            NULL,
    [Col17]       BIT            NULL,
    [Col18]       BIT            NULL,
    [Col19]       BIT            NULL,
    [Col20]       BIT            NULL,
    [Col21]       BIT            NULL,
    [Col22]       BIT            NULL,
    [Col23]       BIT            NULL,
    [Col24]       BIT            NULL,
    [Col25]       BIT            NULL,
    [Col26]       BIT            NULL,
    [Col27]       BIT            NULL,
    [Col28]       BIT            NULL,
    [Col29]       BIT            NULL,
    [Col30]       BIT            NULL,
    [EgyptID]     INT            NULL,
    [RPEID]       INT            NULL,
    [QatarID]     INT            NULL,
    CONSTRAINT [PK_Category] PRIMARY KEY CLUSTERED ([CategoryID] ASC),
    CONSTRAINT [FK_Category_Category1] FOREIGN KEY ([Category2ID]) REFERENCES [dbo].[Category] ([CategoryID])
);

