CREATE TABLE [dbo].[CustomerPayments] (
    [CustomerPaymentID]         INT             IDENTITY (1, 1) NOT NULL,
    [InquiryNumber]             NVARCHAR (50)   NOT NULL,
    [InvoiceNumber]             NVARCHAR (50)   NULL,
    [PaymentNumber]             INT             NOT NULL,
    [PaidAmount]                DECIMAL (18, 2) NULL,
    [ONDate]                    DATETIME        NULL,
    [SumPaid]                   DECIMAL (18, 2) NULL,
    [Deduction]                 BIT             NULL,
    [DeductionNumber]           INT             NULL,
    [DeductionAmount]           DECIMAL (18, 2) NULL,
    [Reason]                    NTEXT           NULL,
    [SumDeduction]              DECIMAL (18, 2) NULL,
    [RestPayment]               DECIMAL (18, 2) NULL,
    [Comment]                   NTEXT           NULL,
    [UserName]                  NVARCHAR (50)   NULL,
    [ModifiedDate]              DATETIME        NULL,
    [PaidAmountCurrencyID]      INT             NULL,
    [PaidAmountRateToEuro]      DECIMAL (18, 2) NULL,
    [PaidAmountInEuro]          DECIMAL (18, 2) NULL,
    [PaidAmountRateDate]        DATETIME        NULL,
    [DeductionAmountCurrencyID] INT             NULL,
    [DeductionAmountRateToEuro] DECIMAL (18, 2) NULL,
    [DeductionAmountInEuro]     DECIMAL (18, 2) NULL,
    [DeductionAmountRateDate]   DATETIME        NULL,
    [IsPaid]                    BIT             NULL,
    [Amount]                    DECIMAL (18, 2) NULL,
    [CurrencyID]                INT             NULL,
    CONSTRAINT [PK_CustomerPayments] PRIMARY KEY CLUSTERED ([CustomerPaymentID] ASC),
    CONSTRAINT [FK_CustomerPayments_Currencies] FOREIGN KEY ([DeductionAmountCurrencyID]) REFERENCES [dbo].[Currencies] ([ID]),
    CONSTRAINT [FK_CustomerPayments_Currencies1] FOREIGN KEY ([PaidAmountCurrencyID]) REFERENCES [dbo].[Currencies] ([ID])
);

