CREATE TABLE [dbo].[OrdersYearlyHistory] (
    [InquiryNumber]              NVARCHAR (50)   NOT NULL,
    [OrderNumber]                NVARCHAR (50)   NULL,
    [CustomerOrderNumber]        NVARCHAR (50)   NULL,
    [SupplierOrderNumber]        NVARCHAR (50)   NULL,
    [OrderDate]                  DATETIME        NULL,
    [DeliveryTime]               INT             NULL,
    [ExpansionDeliveryDate]      DATETIME        NULL,
    [Price]                      MONEY           NULL,
    [RateToEuro]                 DECIMAL (18, 2) NULL,
    [ONDate]                     DATETIME        NULL,
    [PriceInEuro]                MONEY           NULL,
    [DeliveredON]                DATETIME        NULL,
    [Delivered]                  BIT             NULL,
    [Comment]                    NTEXT           NULL,
    [UserName]                   NVARCHAR (50)   NULL,
    [ModifiedDate]               DATETIME        NULL,
    [PriceCommissionBase]        MONEY           NULL,
    [PercentPriceCommissionBase] DECIMAL (18, 4) NULL,
    [OrderStatusID]              INT             NULL,
    [IsSubOrder]                 BIT             NULL,
    [ParentOrderNumber]          NVARCHAR (50)   NULL,
    [BackLog]                    DECIMAL (18, 4) NULL,
    [CompletedGoodsPaidON]       DATETIME        NULL,
    [IsCompletedGoodsPaid]       BIT             NULL,
    [HasGuarantee]               BIT             NULL,
    [PriceBaseID]                INT             NULL,
    [CurrencyID]                 INT             NULL,
    [PaymentTypeID]              INT             NULL,
    CONSTRAINT [PK_OrdersYearlyHistory] PRIMARY KEY CLUSTERED ([InquiryNumber] ASC),
    CONSTRAINT [FK_OrdersYearlyHistory_InquiriesYearlyHistory] FOREIGN KEY ([InquiryNumber]) REFERENCES [dbo].[InquiriesYearlyHistory] ([InquiryNumber]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [FK_OrdersYearlyHistory_PaymentTypes] FOREIGN KEY ([PaymentTypeID]) REFERENCES [dbo].[PaymentTypes] ([ID]),
    CONSTRAINT [FK_OrdersYearlyHistory_PriceBase] FOREIGN KEY ([PriceBaseID]) REFERENCES [dbo].[PriceBase] ([ID])
);

