CREATE TABLE [dbo].[PartialShipment] (
    [PartialShipmentID]  INT             IDENTITY (1, 1) NOT NULL,
    [ShipmentNumber]     NVARCHAR (50)   NULL,
    [InvoiceNumber]      NVARCHAR (150)  NULL,
    [InquiryNumber]      NVARCHAR (50)   NULL,
    [ShipmentDate]       DATETIME        NULL,
    [ItemDescription]    NVARCHAR (250)  NULL,
    [Price]              DECIMAL (18, 4) NULL,
    [CurrencyID]         INT             NULL,
    [RateToEuro]         DECIMAL (18, 2) NULL,
    [RateDate]           DATETIME        NULL,
    [PriceInEuro]        DECIMAL (18, 4) NULL,
    [Remarks]            NVARCHAR (MAX)  NULL,
    [UserName]           NVARCHAR (50)   NULL,
    [ModifiedDate]       DATETIME        NULL,
    [EgyptID]            INT             NULL,
    [RPEID]              INT             NULL,
    [QatarID]            INT             NULL,
    [ShotecNoTemp]       NVARCHAR (50)   NULL,
    [InvoiceValue]       DECIMAL (18, 4) NULL,
    [InvoiceValueinEuro] DECIMAL (18, 4) NULL,
    CONSTRAINT [PK_ParitalShipment] PRIMARY KEY CLUSTERED ([PartialShipmentID] ASC),
    CONSTRAINT [FK_ParitalShipment_Inquiries] FOREIGN KEY ([InquiryNumber]) REFERENCES [dbo].[Inquiries] ([InquiryNumber]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [FK_PartialShipment_Currencies] FOREIGN KEY ([CurrencyID]) REFERENCES [dbo].[Currencies] ([ID])
);

