CREATE TABLE [dbo].[PartialOrderYearlyHistory] (
    [PartialOrderYearlyHistoryID] INT             NOT NULL,
    [ItemTagNumber]               NVARCHAR (50)   NULL,
    [ItemModelSize]               NVARCHAR (150)  NULL,
    [InquiryNumber]               NVARCHAR (50)   NULL,
    [Quantity]                    INT             NULL,
    [ProductTypeID]               INT             NULL,
    [ProductID]                   INT             NULL,
    [SupplierID]                  INT             NULL,
    [ItemOfferPrice]              DECIMAL (18, 4) NULL,
    [ItemOfferRateToEuro]         DECIMAL (18, 4) NULL,
    [ItemOfferRateDate]           DATETIME        NULL,
    [TotalItemOfferPrice]         DECIMAL (18, 4) NULL,
    [TotalItemOfferPriceInEuro]   DECIMAL (18, 4) NULL,
    [ItemOrderPrice]              DECIMAL (18, 4) NULL,
    [ItemOrderPriceRateToEuro]    DECIMAL (18, 4) NULL,
    [TotalItemOrderPrice]         DECIMAL (18, 4) NULL,
    [TotalItemOrderPriceInEuro]   DECIMAL (18, 4) NULL,
    [OrderPriceRateDate]          DATETIME        NULL,
    [IsOrdered]                   BIT             NULL,
    [Remarks]                     NVARCHAR (MAX)  NULL,
    [ParialDeliveryStatusID]      INT             NULL,
    [UserName]                    NVARCHAR (50)   NULL,
    [ModifiedDate]                DATETIME        NULL,
    [ItemOfferCurrencyID]         INT             NULL,
    [ItemOrderPriceCurrencyID]    INT             NULL,
    CONSTRAINT [PK_PartialOrderYearlyHistory] PRIMARY KEY CLUSTERED ([PartialOrderYearlyHistoryID] ASC),
    CONSTRAINT [FK_PartialDelivery_OrdersYearlyHistory] FOREIGN KEY ([InquiryNumber]) REFERENCES [dbo].[InquiriesYearlyHistory] ([InquiryNumber]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [FK_PartialOrderYearlyHistory_Currencies] FOREIGN KEY ([ItemOfferCurrencyID]) REFERENCES [dbo].[Currencies] ([ID]),
    CONSTRAINT [FK_PartialOrderYearlyHistory_Currencies1] FOREIGN KEY ([ItemOrderPriceCurrencyID]) REFERENCES [dbo].[Currencies] ([ID]),
    CONSTRAINT [FK_PartialOrderYearlyHistory_ProductTypes] FOREIGN KEY ([ProductTypeID]) REFERENCES [dbo].[ProductTypes] ([ProductTypeID])
);

