CREATE TABLE [dbo].[PartialOrder] (
    [PartialOrderID]            INT             IDENTITY (1, 1) NOT NULL,
    [ItemTagNumber]             NVARCHAR (50)   NULL,
    [ItemModelSize]             NVARCHAR (150)  NULL,
    [InquiryNumber]             NVARCHAR (50)   NULL,
    [Quantity]                  INT             NULL,
    [ProductTypeID]             INT             NULL,
    [ProductID]                 INT             NULL,
    [SupplierID]                INT             NULL,
    [ItemOfferPrice]            DECIMAL (18, 4) NULL,
    [ItemOfferCurrencyID]       INT             NULL,
    [ItemOfferRateToEuro]       DECIMAL (18, 4) NULL,
    [ItemOfferRateDate]         DATETIME        NULL,
    [TotalItemOfferPrice]       DECIMAL (18, 4) NULL,
    [TotalItemOfferPriceInEuro] DECIMAL (18, 4) NULL,
    [ItemOrderPrice]            DECIMAL (18, 4) NULL,
    [ItemOrderPriceCurrencyID]  INT             NULL,
    [ItemOrderPriceRateToEuro]  DECIMAL (18, 4) NULL,
    [TotalItemOrderPrice]       DECIMAL (18, 4) NULL,
    [TotalItemOrderPriceInEuro] DECIMAL (18, 4) NULL,
    [OrderPriceRateDate]        DATETIME        NULL,
    [IsOrdered]                 BIT             NULL,
    [Remarks]                   NVARCHAR (MAX)  NULL,
    [ParialDeliveryStatusID]    INT             NULL,
    [UserName]                  NVARCHAR (50)   NULL,
    [ModifiedDate]              DATETIME        NULL,
    [EgyptID]                   INT             NULL,
    [RPEID]                     INT             NULL,
    [QatarID]                   INT             NULL,
    [ShotecNoTemp]              NVARCHAR (50)   NULL,
    CONSTRAINT [PK_PartialDeliverey] PRIMARY KEY CLUSTERED ([PartialOrderID] ASC),
    CONSTRAINT [FK_PartialDelivery_Orders] FOREIGN KEY ([InquiryNumber]) REFERENCES [dbo].[Inquiries] ([InquiryNumber]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [FK_PartialDelivery_ProductTypes] FOREIGN KEY ([ProductTypeID]) REFERENCES [dbo].[ProductTypes] ([ProductTypeID]),
    CONSTRAINT [FK_PartialOrder_Currencies] FOREIGN KEY ([ItemOfferCurrencyID]) REFERENCES [dbo].[Currencies] ([ID]),
    CONSTRAINT [FK_PartialOrder_Currencies1] FOREIGN KEY ([ItemOrderPriceCurrencyID]) REFERENCES [dbo].[Currencies] ([ID])
);

