CREATE TABLE [dbo].[Product] (
    [ProductID]       INT             IDENTITY (1, 1) NOT NULL,
    [CategoryID]      INT             NULL,
    [Name]            NVARCHAR (MAX)  NULL,
    [Col1]            DECIMAL (18, 2) NULL,
    [Col2]            DECIMAL (18, 2) NULL,
    [Col3]            DECIMAL (18, 2) NULL,
    [Col4]            DECIMAL (18, 2) NULL,
    [Col5]            DECIMAL (18, 2) NULL,
    [Col6]            DECIMAL (18, 2) NULL,
    [Col7]            DECIMAL (18, 2) NULL,
    [Col8]            DECIMAL (18, 2) NULL,
    [Col9]            DECIMAL (18, 2) NULL,
    [Col10]           DECIMAL (18, 2) NULL,
    [Col11]           BIT             NULL,
    [Col12]           BIT             NULL,
    [Col13]           BIT             NULL,
    [Col14]           BIT             NULL,
    [Col15]           BIT             NULL,
    [Col16]           BIT             NULL,
    [Col17]           BIT             NULL,
    [Col18]           BIT             NULL,
    [Col19]           BIT             NULL,
    [Col20]           BIT             NULL,
    [Col21]           NVARCHAR (MAX)  NULL,
    [Col22]           NVARCHAR (MAX)  NULL,
    [Col23]           NVARCHAR (MAX)  NULL,
    [Col24]           NVARCHAR (MAX)  NULL,
    [Col25]           NVARCHAR (MAX)  NULL,
    [Col26]           NVARCHAR (MAX)  NULL,
    [Col27]           NVARCHAR (MAX)  NULL,
    [Col28]           NVARCHAR (MAX)  NULL,
    [Col29]           NVARCHAR (MAX)  NULL,
    [Col30]           NVARCHAR (MAX)  NULL,
    [ProductTypeID]   INT             NULL,
    [CostPrice]       DECIMAL (18, 2) NULL,
    [CurrencyID]      INT             NULL,
    [RateToEuro]      DECIMAL (18, 2) NULL,
    [CostPriceInEuro] DECIMAL (18, 2) NULL,
    CONSTRAINT [PK_Product] PRIMARY KEY CLUSTERED ([ProductID] ASC),
    CONSTRAINT [FK_Product_Category] FOREIGN KEY ([CategoryID]) REFERENCES [dbo].[Category] ([CategoryID])
);

