CREATE TABLE [dbo].[Projects] (
    [ID]                      INT             IDENTITY (1, 1) NOT NULL,
    [ProjectCode]             NVARCHAR (50)   NOT NULL,
    [ProjectName]             NVARCHAR (100)  NULL,
    [ProjectLocation]         NVARCHAR (100)  NULL,
    [ProjectDescription]      NTEXT           NULL,
    [OwnerID]                 INT             NULL,
    [FinalProduct]            NVARCHAR (500)  NULL,
    [StartDate]               DATETIME        NULL,
    [EstimatedCost]           DECIMAL (18, 2) NULL,
    [EstimatedCostCurrencyID] INT             NULL,
    [Shareholders]            NVARCHAR (250)  NULL,
    [LicenseBy]               NVARCHAR (250)  NULL,
    [EngineeringBy]           NVARCHAR (250)  NULL,
    [EngineeringByID]         INT             NULL,
    [ProcurementBy]           NVARCHAR (250)  NULL,
    [ProcurementByID]         INT             NULL,
    [Contractor]              NVARCHAR (500)  NULL,
    [ContractorID]            INT             NULL,
    [EPC]                     NVARCHAR (250)  NULL,
    [VendorlistBy]            NVARCHAR (500)  NULL,
    [ProjectStatusID]         INT             NULL,
    [ContactTitle]            NCHAR (10)      NULL,
    [ContactName]             NVARCHAR (100)  NULL,
    [ContactPosition]         NVARCHAR (150)  NULL,
    [ContactHomePhone]        NVARCHAR (50)   NULL,
    [ContactWorkPhone]        NVARCHAR (50)   NULL,
    [ContactMobile]           NVARCHAR (50)   NULL,
    [ContactEmail]            NVARCHAR (50)   NULL,
    [ContactAddress]          NVARCHAR (255)  NULL,
    [ContactCountry]          NVARCHAR (50)   NULL,
    [ContactCity]             NVARCHAR (50)   NULL,
    [ContactZip]              NVARCHAR (50)   NULL,
    [ContactFax]              NVARCHAR (50)   NULL,
    [ContactCompany]          NVARCHAR (250)  NULL,
    [UserName]                NVARCHAR (50)   NULL,
    [ModifiedDate]            DATETIME        NULL,
    [BranchID]                INT             NULL,
    [IsGeneral]               BIT             NULL,
    [EgyptID]                 INT             NULL,
    [RPEID]                   INT             NULL,
    [QatarID]                 INT             NULL,
    [IsOwnerRegistered]       BIT             NULL,
    CONSTRAINT [PK_Projects] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_Projects_ProjectsStatuses] FOREIGN KEY ([ProjectStatusID]) REFERENCES [dbo].[ProjectsStatuses] ([ID])
);

