CREATE TABLE [Person].[PersonExtra] (
    [PersonID]                INT            NOT NULL,
    [NationalityCode]         CHAR (3)       NULL,
    [Gender]                  NCHAR (1)      NULL,
    [Religion]                NVARCHAR (50)  NULL,
    [BirthDate]               DATETIME       NULL,
    [BirthPlace]              NVARCHAR (50)  NULL,
    [MaritalStatus]           NVARCHAR (50)  NULL,
    [SpauseName]              NVARCHAR (50)  NULL,
    [EmergencyContactName]    NVARCHAR (150) NULL,
    [EmergencyContactAddress] NVARCHAR (250) NULL,
    [EmergencyContactNumber]  NVARCHAR (50)  NULL,
    [EmergencyContactEmail]   NVARCHAR (150) NULL,
    [HireDate]                DATETIME       NULL,
    [LeaveDate]               DATETIME       NULL,
    [IsResponsibleEngineer]   BIT            NULL,
    [Position]                NVARCHAR (50)  NULL,
    [Salary]                  MONEY          NULL,
    [SalaryCurrencyID]        INT            NULL,
    [ManagerId]               INT            NULL,
    [OfferApprove]            BIT            NULL,
    [OfferPrepare]            BIT            NULL,
    [OtherInformation]        NVARCHAR (MAX) NULL,
    [NumOfVacation]           INT            NULL,
    [EmployeeTypeID]          INT            NULL,
    [BranchID]                INT            NULL,
    CONSTRAINT [PK_PersonExtra] PRIMARY KEY CLUSTERED ([PersonID] ASC),
    CONSTRAINT [FK_PersonExtra_Person] FOREIGN KEY ([PersonID]) REFERENCES [Person].[Person] ([BusinessEntityId]) ON DELETE CASCADE ON UPDATE CASCADE
);

