CREATE PROCEDURE [dbo].[InsertNewCalculationSheetDetail]
    @CalculationSheetID int,
    @CurrencyID int,
    @ItemID int  = null ,
    @ItemNumber int,
    @PriceBase int,
    @PriceBaseID int,
    @PriceInEuro decimal(18,2),
    @ProductID int,
    @Quantity decimal(18,2),
    @RateToEuro decimal(18,2),
    @SubTotalCost decimal(18,2),
    @SubTotalPrice decimal(18,2),
    @UnitCost decimal(18,2),
    @UnitPrice decimal(18,2),
    @UnitPriceWithTaxes decimal(18,2),
    @RateToOfferCurrency decimal(18,2),
    @PriceInOfferCurrency decimal(18,2),
	@ParentID int,
	@ItemDescription nvarchar(250),
	@Margin decimal(5,2)
AS
INSERT INTO [dbo].[CalculationSheetDetail] (
    [CalculationSheetID],
    [CurrencyID],
    [ItemID],
    [ItemNumber],
    [PriceBase],
    [PriceBaseID],
    [PriceInEuro],
    [ProductID],
    [Quantity],
    [RateToEuro],
    [SubTotalCost],
    [SubTotalPrice],
    [UnitCost],
    [UnitPrice],
    [UnitPriceWithTaxes],
    [RateToOfferCurrency],
    [PriceInOfferCurrency],
	ParentID,
	ItemDescription ,
	Margin)
Values (
    @CalculationSheetID,
    @CurrencyID,
    @ItemID,
    @ItemNumber,
    @PriceBase,
    @PriceBaseID,
    @PriceInEuro,
    @ProductID,
    @Quantity,
    @RateToEuro,
    @SubTotalCost,
    @SubTotalPrice,
    @UnitCost,
    @UnitPrice,
    @UnitPriceWithTaxes,
    @RateToOfferCurrency ,
    @PriceInOfferCurrency,
	@ParentID,
	@ItemDescription ,
	@Margin)
IF @@ROWCOUNT > 0
Select * from CalculationSheetDetail
Where [CalculationSheetDetailID] = @@identity
