CREATE PROCEDURE [dbo].[InsertNewInquiries]
    @InquiryNumber nvarchar(50),
    @ResponsibleEngineerID int,
    @InquiryTypeID int,
    @CustomerID int,
    @CustomerInquiryNumber nvarchar(50),
    @ProjectID int,
    @ProductID int,
    @InquiryDate datetime,
    @BidDueDate datetime,
    @SupplierID int,
    @SupplierQuotationNumber nvarchar(50),
    @QuotationPrice money,
    @CurrencyID int,
    @RateToEuro decimal(18,2),
    @ONDate datetime,
    @QuotationPriceInEuro money,
   -- @InquiryStatus nvarchar(50),
    @Comment ntext,
    @UserName nvarchar(50),
    @ModifiedDate datetime,
    @ProductDescription varchar(150),
    @ShotecNo varchar(50),
    @OnHold bit,
    @InquiryStatusID int,
	@OrderPercentage decimal(18,4),
	@LostPercentage decimal(18,4),
	@CancelledPercentage decimal(18,4),
	@LateResponsePercentage decimal(18,4),
	@ProjectTypeID int,
	@OfferDate datetime,
	@ParentInquiryNumber nvarchar(50),
	@IsSubOffer bit,
	@ProductTypeID int,
	@OrderChanceID int,
	@HasGuarantee bit,
	@BranchID int,
	@PriceBaseID	int	,
	@PaymentBaseID	int	,
	@FileNo nvarchar(50)
AS
INSERT INTO [dbo].[Inquiries] (
    [InquiryNumber],
    [ResponsibleEngineerID],
    [InquiryTypeID],
    [CustomerID],
    [CustomerInquiryNumber],
    [ProjectID],
    [ProductID],
    [InquiryDate],
    [BidDueDate],
    [SupplierID],
    [SupplierQuotationNumber],
    [QuotationPrice],
    [CurrencyID],
    [RateToEuro],
    [ONDate],
    [QuotationPriceInEuro],
    --[InquiryStatus],
    [Comment],
    [UserName],
    [ModifiedDate],
    [ProductDescription],
    [ShotecNo],
    [OnHold],
    [InquiryStatusID],
    [OrderPercentage],
    [LostPercentage],
    [CancelledPercentage],
    [LateResponsePercentage],
    [ProjectTypeID],
    [OfferDate],
    [ParentInquiryNumber],
    IsSubOffer,
    ProductTypeID,
    OrderChanceID,
    HasGuarantee,
    BranchID,
	PriceBaseID,
	PaymentBaseID ,
	FileNo)
Values (
    @InquiryNumber,
    @ResponsibleEngineerID,
    @InquiryTypeID,
    @CustomerID,
    @CustomerInquiryNumber,
    @ProjectID,
    @ProductID,
    @InquiryDate,
    @BidDueDate,
    @SupplierID,
    @SupplierQuotationNumber,
    @QuotationPrice,
    @CurrencyID,
    @RateToEuro,
    @ONDate,
    @QuotationPriceInEuro,
    --@InquiryStatus,
    @Comment,
    @UserName,
    @ModifiedDate,
    @ProductDescription,
    @ShotecNo,
    @OnHold,
    @InquiryStatusID,
    @OrderPercentage,
    @LostPercentage,
    @CancelledPercentage,
    @LateResponsePercentage,
    @ProjectTypeID,
    @OfferDate,
    @ParentInquiryNumber,
    @IsSubOffer,
    @ProductTypeID,
    @OrderChanceID,
    @HasGuarantee,
    @BranchID,
	@PriceBaseID,
	@PaymentBaseID,
	@FileNo)
    
IF @@ROWCOUNT > 0
Select Inquiries.* ,ProjectTypes.ProjectType as InquiryStatus
from Inquiries, ProjectTypes
Where [InquiryNumber] = @InquiryNumber and
      ProjectTypes.ID = Inquiries.ProjectTypeID
