CREATE PROCEDURE [dbo].[InsertNewAgents]
    @AgentName nvarchar(100),
    @AgentAddress nvarchar(300),
    @AgentWebSite nvarchar(100),
    @ContactTitle nvarchar(10),
    @ContactName nvarchar(100),
    @ContactDisplayName nvarchar(150),
    @ContactHomePhone nvarchar(50),
    @ContactWorkPhone nvarchar(50),
    @ContactMobile nvarchar(50),
    @ContactEmail nvarchar(50),
    @ContactAddress nvarchar(255),
    @ContactCountry nvarchar(50),
    @ContactCity nvarchar(50),
    @ContactZip nvarchar(50),
    @ContactFax nvarchar(50),
    @UserName nvarchar(50),
    @ModifiedDate datetime
AS
INSERT INTO [dbo].[Agents] (
    [AgentName],
    [AgentAddress],
    [AgentWebSite],
    [ContactTitle],
    [ContactName],
    [ContactDisplayName],
    [ContactHomePhone],
    [ContactWorkPhone],
    [ContactMobile],
    [ContactEmail],
    [ContactAddress],
    [ContactCountry],
    [ContactCity],
    [ContactZip],
    [ContactFax],
    [UserName],
    [ModifiedDate])
Values (
    @AgentName,
    @AgentAddress,
    @AgentWebSite,
    @ContactTitle,
    @ContactName,
    @ContactDisplayName,
    @ContactHomePhone,
    @ContactWorkPhone,
    @ContactMobile,
    @ContactEmail,
    @ContactAddress,
    @ContactCountry,
    @ContactCity,
    @ContactZip,
    @ContactFax,
    @UserName,
    @ModifiedDate)
IF @@ROWCOUNT > 0
Select * from Agents
Where [AgentID] = @@identity
