CREATE PROCEDURE [dbo].[UpdateInquiries]
    @InquiryNumber nvarchar(50),
    @OldInquiryNumber nvarchar(50),
    @ResponsibleEngineerID int,
    @InquiryTypeID int,
    @CustomerID int,
    @CustomerInquiryNumber nvarchar(50),
    @ProjectID int,
    @ProductID int,
    @InquiryDate datetime,
    @BidDueDate datetime,
    @SupplierID int,
    @SupplierQuotationNumber nvarchar(50),
    @QuotationPrice money,
    @CurrencyID int,
    @RateToEuro decimal(18,2),
    @ONDate datetime,
    @QuotationPriceInEuro money,
    --@InquiryStatus nvarchar(50),
    @Comment ntext,
    @UserName nvarchar(50),
    @ModifiedDate datetime,
    @ProductDescription varchar(150),
    @ShotecNo varchar(50),
    @OnHold bit,
    @InquiryStatusID int,
    @OrderPercentage decimal(18,4),
    @LostPercentage decimal(18,4),
	@CancelledPercentage decimal(18,4),
	@LateResponsePercentage decimal(18,4),
    @ProjectTypeID int ,
	@OfferDate datetime,
	@ParentInquiryNumber nvarchar(50),
	@IsSubOffer bit,
	@ProductTypeID int,
	@OrderChanceID int,
	@HasGuarantee bit,
	@BranchID int,
	@PriceBaseID	int	,
	@PaymentBaseID	int	,
	@FileNo nvarchar(50)
AS
UPDATE [dbo].[Inquiries]
SET
    InquiryNumber = @InquiryNumber,
    ResponsibleEngineerID = @ResponsibleEngineerID,
    InquiryTypeID = @InquiryTypeID,
    CustomerID = @CustomerID,
    CustomerInquiryNumber = @CustomerInquiryNumber,
    ProjectID = @ProjectID,
    ProductID = @ProductID,
    InquiryDate = @InquiryDate,
    BidDueDate = @BidDueDate,
    SupplierID = @SupplierID,
    SupplierQuotationNumber = @SupplierQuotationNumber,
    QuotationPrice = @QuotationPrice,
    CurrencyID = @CurrencyID,
    RateToEuro = @RateToEuro,
    ONDate = @ONDate,
    QuotationPriceInEuro = @QuotationPriceInEuro,
   -- InquiryStatus = @InquiryStatus,
    Comment = @Comment,
    UserName = @UserName,
    ModifiedDate = @ModifiedDate,
    ProductDescription = @ProductDescription,
    ShotecNo = @ShotecNo,
    OnHold = @OnHold,
    InquiryStatusID = @InquiryStatusID,
    OrderPercentage = @OrderPercentage,
    LostPercentage = @LostPercentage,
    CancelledPercentage = @CancelledPercentage,
    LateResponsePercentage = @LateResponsePercentage,
    ProjectTypeID = @ProjectTypeID,
	OfferDate = @OfferDate ,
	ParentInquiryNumber = @ParentInquiryNumber,
	IsSubOffer = @IsSubOffer,
	ProductTypeID = @ProductTypeID,
	OrderChanceID = @OrderChanceID,
	HasGuarantee = @HasGuarantee,
	BranchID = @BranchID,
	PriceBaseID = @PriceBaseID,
	PaymentBaseID = @PaymentBaseID ,
	FileNo  = @FileNo 
WHERE [InquiryNumber] = @OLDInquiryNumber
--IF @@ROWCOUNT > 0
--Select Inquiries.* ,ProjectTypes.ProjectType as InquiryStatus
--from Inquiries, ProjectTypes
--Where [InquiryNumber] = @InquiryNumber and
--      ProjectTypes.ID = Inquiries.ProjectTypeID
