CREATE PROCEDURE [dbo].[UpdateOrders]
    @InquiryNumber nvarchar(50),
    @OldInquiryNumber nvarchar(50),
    @OrderNumber nvarchar(50),
    @CustomerOrderNumber nvarchar(50),
    @SupplierOrderNumber nvarchar(50),
    @OrderDate datetime,
    @DeliveryTime int,
    @ExpansionDeliveryDate datetime,
    @PaymentTypeID int,
    @PriceBaseID int,
    @Price money,
    @CurrencyID int,
    @RateToEuro decimal(18,2),
    @ONDate datetime,
    @PriceInEuro money,
    @DeliveredON datetime,
    @Delivered bit,
    @Comment ntext,
    @UserName nvarchar(50),
    @ModifiedDate datetime,
    @PriceCommissionBase money,
    @PercentPriceCommissionBase decimal(18,4),
    @OrderStatusID int,
    @ParentOrderNumber nvarchar(50),
    @IsSubOrder bit,
    @BackLog decimal(18,4),
    @CompletedGoodsPaidON datetime,
    @IsCompletedGoodsPaid bit,
    @HasGuarantee bit,
	@DeliveryTimePeriodID int,
	@DiscountValue decimal(18,4)
AS
UPDATE [dbo].[Orders]
SET
    InquiryNumber = @InquiryNumber,
    OrderNumber = @OrderNumber,
    CustomerOrderNumber = @CustomerOrderNumber,
    SupplierOrderNumber = @SupplierOrderNumber,
    OrderDate = @OrderDate,
    DeliveryTime = @DeliveryTime,
    ExpansionDeliveryDate = @ExpansionDeliveryDate,
    PaymentTypeID = @PaymentTypeID,
    PriceBaseID = @PriceBaseID,
    Price = @Price,
    CurrencyID = @CurrencyID,
    RateToEuro = @RateToEuro,
    ONDate = @ONDate,
    PriceInEuro = @PriceInEuro,
    DeliveredON = @DeliveredON,
    Delivered = @Delivered,
    Comment = @Comment,
    UserName = @UserName,
    ModifiedDate = @ModifiedDate,
    PriceCommissionBase = @PriceCommissionBase,
    PercentPriceCommissionBase = @PercentPriceCommissionBase,
    OrderStatusID = @OrderStatusID,
    ParentOrderNumber = @ParentOrderNumber,
    IsSubOrder = @IsSubOrder,
    BackLog = @BackLog,
    CompletedGoodsPaidON = @CompletedGoodsPaidON,
    IsCompletedGoodsPaid = @IsCompletedGoodsPaid,
    HasGuarantee = @HasGuarantee,
	DeliveryTimePeriodID = @DeliveryTimePeriodID ,
	DiscountValue=@DiscountValue
WHERE [InquiryNumber] = @OLDInquiryNumber
IF @@ROWCOUNT > 0
Select * From Orders 
Where [InquiryNumber] = @InquiryNumber
