CREATE VIEW [dbo].[ViewProjectInquiryLostOrderDeliveredCompletedYearlyHistory]
AS
SELECT     dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.ProjectSerialNumber, dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.ShotecNo, 
                      dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.ResponsibleEngineer, dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.ClientName, 
                      dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.ClientWebsite, dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.ClientInquiryNumber, 
                      dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.InquiryDate, dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.ProjectStatus, 
                      dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.InquiryTypeID, dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.SupplierName, 
                      dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.SupplierQuotationNumber, dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.QuotationPrice, 
                      dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.QuotationCurrency, dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.QuotationRateToEURO, 
                      dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.QuotationRateDate, dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.QuotationPriceInEuro, 
                      dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.BidDueDate, dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.ModifiedDate, 
                      dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.OnHold, dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.UserName, 
                      dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.ProjectName, dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.ProjectLocation, 
                      dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.ProjectOwnerName, dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.ProjectDescription, 
                      dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.ProductName, dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.CategoryName, 
                      dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.ProductDescription, dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.ProjectComment, 
                      dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.ReasonName, dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.LostReasonID, 
                      dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.LostWinnerName, dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.LostWinnerPrice, 
                      dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.LostWinnerPriceInEuro, dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.LostWinnerRateToEuro, 
                      dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.LostWinnerRateDate, dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.LostWinnerPriceCurrencyID, 
                      dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.ShotecOrderNumber, dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.CustomerOrderNumber, 
                      dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.SupplierOrderNumber, dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.DeliveryTime, 
                      dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.DeliveredON, dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.Delivered, 
                      dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.ExpectedDeliveryDate, dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.PaymentTypeID, 
                      dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.PriceBaseID, dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.OrderPrice, 
                      dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.OrderCurrencyID, dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.OrderRateToEuro, 
                      dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.OrderRateDate, dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.OrderPriceInEuro, 
                      dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.OrderDate, dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.OrderPriceCommissionBase, 
                      dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.OrderPercentPriceCommissionBase, dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.InquiryStatus, 
                      dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.SupplierID, dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.OrderStatus, 
                      dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.LostDate, dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.ProjectTypeID, 
                      dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.OfferDate, dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.ParentInquiryNumber, 
                      dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.ParentOrderNumber, dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.IsSubOrder, 
                      dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.IsSubOffer, dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.IsSubLost, 
                      dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.LostParentInquiryNumber, dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.CustomerID, 
                      dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.LostComment, dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.ProductType, 
                      dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.ProductTypeID, dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.OrderPercentage, 
                      dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.LostPercentage, dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.CancelledPercentage, 
                      dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.LateResponsePercentage, dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.BackLog, 
                      dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.OrderChanceID, dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.OrderChance, 
                      dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.CompletedGoodsPaidON, dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.IsCompletedGoodsPaid, 
                      dbo.CompletedProjectsYearlyHistory.HasCommission, dbo.CompletedProjectsYearlyHistory.IsAllGuranteesClosed, 
                      dbo.CompletedProjectsYearlyHistory.GuaranteesClosedDate, dbo.CompletedProjectsYearlyHistory.IsAllCommissionPaid, 
                      dbo.CompletedProjectsYearlyHistory.AllCommssionPaidDate, dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.CompanyCode, 
                      dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.InquiryHasGuarantee, dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.OrderHasGuarantee, 
                      dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.OrderStatusID, dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.ProjectID, 
                      dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.InquiryType, dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.QuotationCurrencyCode, 
                      dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.LostWinnerPriceCurrencyCode, dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.PriceBaseCode, 
                      dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.PaymentType, dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.OrderCurrencyCode, 
                      dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.LanguageId, dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.ResponsibleEngineerDisplayName, 
                      dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.ResponsibleEngineerID, dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.LostReasonCode, 
                      dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.Year, dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.BranchID
FROM         dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory LEFT OUTER JOIN
                      dbo.CompletedProjectsYearlyHistory ON 
                      dbo.ViewProjectInquiryLostOrderDeliveredYearlyHistory.ProjectSerialNumber = dbo.CompletedProjectsYearlyHistory.InquiryNumber
