CREATE VIEW [dbo].[ViewProjectInquiryLostOrderDeliveredCompleted]
AS
SELECT     dbo.ViewProjectInquiryLostOrderDelivered.ProjectSerialNumber, dbo.ViewProjectInquiryLostOrderDelivered.ShotecNo, 
                      dbo.ViewProjectInquiryLostOrderDelivered.ResponsibleEngineer, dbo.ViewProjectInquiryLostOrderDelivered.ClientName, 
                      dbo.ViewProjectInquiryLostOrderDelivered.ClientWebsite, dbo.ViewProjectInquiryLostOrderDelivered.ClientInquiryNumber, 
                      dbo.ViewProjectInquiryLostOrderDelivered.InquiryDate, dbo.ViewProjectInquiryLostOrderDelivered.ProjectStatus, 
                      dbo.ViewProjectInquiryLostOrderDelivered.InquiryTypeID, dbo.ViewProjectInquiryLostOrderDelivered.SupplierName, 
                      dbo.ViewProjectInquiryLostOrderDelivered.SupplierQuotationNumber, dbo.ViewProjectInquiryLostOrderDelivered.QuotationPrice, 
                      dbo.ViewProjectInquiryLostOrderDelivered.QuotationCurrency, dbo.ViewProjectInquiryLostOrderDelivered.QuotationRateToEURO, 
                      dbo.ViewProjectInquiryLostOrderDelivered.QuotationRateDate, dbo.ViewProjectInquiryLostOrderDelivered.QuotationPriceInEuro, 
                      dbo.ViewProjectInquiryLostOrderDelivered.BidDueDate, dbo.ViewProjectInquiryLostOrderDelivered.ModifiedDate, dbo.ViewProjectInquiryLostOrderDelivered.OnHold, 
                      dbo.ViewProjectInquiryLostOrderDelivered.UserName, dbo.ViewProjectInquiryLostOrderDelivered.ProjectName, 
                      dbo.ViewProjectInquiryLostOrderDelivered.ProjectLocation, dbo.ViewProjectInquiryLostOrderDelivered.ProjectOwnerName, 
                      dbo.ViewProjectInquiryLostOrderDelivered.ProjectDescription, dbo.ViewProjectInquiryLostOrderDelivered.ProductName, 
                      dbo.ViewProjectInquiryLostOrderDelivered.CategoryName, dbo.ViewProjectInquiryLostOrderDelivered.ProductDescription, 
                      dbo.ViewProjectInquiryLostOrderDelivered.ProjectComment, dbo.ViewProjectInquiryLostOrderDelivered.ReasonName, 
                      dbo.ViewProjectInquiryLostOrderDelivered.LostReasonID, dbo.ViewProjectInquiryLostOrderDelivered.LostWinnerName, 
                      dbo.ViewProjectInquiryLostOrderDelivered.LostWinnerPrice, dbo.ViewProjectInquiryLostOrderDelivered.LostWinnerPriceInEuro, 
                      dbo.ViewProjectInquiryLostOrderDelivered.LostWinnerRateToEuro, dbo.ViewProjectInquiryLostOrderDelivered.LostWinnerRateDate, 
                      dbo.ViewProjectInquiryLostOrderDelivered.LostWinnerPriceCurrencyID, dbo.ViewProjectInquiryLostOrderDelivered.ShotecOrderNumber, 
                      dbo.ViewProjectInquiryLostOrderDelivered.CustomerOrderNumber, dbo.ViewProjectInquiryLostOrderDelivered.SupplierOrderNumber, 
                      dbo.ViewProjectInquiryLostOrderDelivered.DeliveryTime, dbo.ViewProjectInquiryLostOrderDelivered.DeliveredON, 
                      dbo.ViewProjectInquiryLostOrderDelivered.Delivered, dbo.ViewProjectInquiryLostOrderDelivered.ExpectedDeliveryDate, 
                      dbo.ViewProjectInquiryLostOrderDelivered.PaymentTypeID, dbo.ViewProjectInquiryLostOrderDelivered.PriceBaseID, 
                      dbo.ViewProjectInquiryLostOrderDelivered.OrderPrice, dbo.ViewProjectInquiryLostOrderDelivered.OrderCurrencyID, 
                      dbo.ViewProjectInquiryLostOrderDelivered.OrderRateToEuro, dbo.ViewProjectInquiryLostOrderDelivered.OrderRateDate, 
                      dbo.ViewProjectInquiryLostOrderDelivered.OrderPriceInEuro, dbo.ViewProjectInquiryLostOrderDelivered.OrderDate, 
                      dbo.ViewProjectInquiryLostOrderDelivered.OrderPriceCommissionBase, dbo.ViewProjectInquiryLostOrderDelivered.OrderPercentPriceCommissionBase, 
                      dbo.ViewProjectInquiryLostOrderDelivered.InquiryStatus, dbo.ViewProjectInquiryLostOrderDelivered.SupplierID, 
                      dbo.ViewProjectInquiryLostOrderDelivered.OrderStatus, dbo.ViewProjectInquiryLostOrderDelivered.LostDate, 
                      dbo.ViewProjectInquiryLostOrderDelivered.ProjectTypeID, dbo.ViewProjectInquiryLostOrderDelivered.OfferDate, 
                      dbo.ViewProjectInquiryLostOrderDelivered.ParentInquiryNumber, dbo.ViewProjectInquiryLostOrderDelivered.ParentOrderNumber, 
                      dbo.ViewProjectInquiryLostOrderDelivered.IsSubOrder, dbo.ViewProjectInquiryLostOrderDelivered.IsSubOffer, dbo.ViewProjectInquiryLostOrderDelivered.IsSubLost, 
                      dbo.ViewProjectInquiryLostOrderDelivered.LostParentInquiryNumber, dbo.ViewProjectInquiryLostOrderDelivered.CustomerID, 
                      dbo.ViewProjectInquiryLostOrderDelivered.LostComment, dbo.ViewProjectInquiryLostOrderDelivered.ProductType, 
                      dbo.ViewProjectInquiryLostOrderDelivered.ProductTypeID, dbo.ViewProjectInquiryLostOrderDelivered.OrderPercentage, 
                      dbo.ViewProjectInquiryLostOrderDelivered.LostPercentage, dbo.ViewProjectInquiryLostOrderDelivered.CancelledPercentage, 
                      dbo.ViewProjectInquiryLostOrderDelivered.LateResponsePercentage, dbo.ViewProjectInquiryLostOrderDelivered.BackLog, 
                      dbo.ViewProjectInquiryLostOrderDelivered.OrderChanceID, dbo.ViewProjectInquiryLostOrderDelivered.OrderChance, 
                      dbo.ViewProjectInquiryLostOrderDelivered.CompletedGoodsPaidON, dbo.ViewProjectInquiryLostOrderDelivered.IsCompletedGoodsPaid, 
                      dbo.CompletedProjects.HasCommission, dbo.CompletedProjects.IsAllGuranteesClosed, dbo.CompletedProjects.GuaranteesClosedDate, 
                      dbo.CompletedProjects.IsAllCommissionPaid, dbo.CompletedProjects.AllCommssionPaidDate, dbo.ViewProjectInquiryLostOrderDelivered.CompanyCode, 
                      dbo.ViewProjectInquiryLostOrderDelivered.InquiryHasGuarantee, dbo.ViewProjectInquiryLostOrderDelivered.OrderHasGuarantee, 
                      dbo.ViewProjectInquiryLostOrderDelivered.OrderStatusID, dbo.ViewProjectInquiryLostOrderDelivered.ProjectID, 
                      dbo.ViewProjectInquiryLostOrderDelivered.InquiryType, dbo.ViewProjectInquiryLostOrderDelivered.QuotationCurrencyCode, 
                      dbo.ViewProjectInquiryLostOrderDelivered.LostWinnerPriceCurrencyCode, dbo.ViewProjectInquiryLostOrderDelivered.PriceBaseCode, 
                      dbo.ViewProjectInquiryLostOrderDelivered.PaymentType, dbo.ViewProjectInquiryLostOrderDelivered.OrderCurrencyCode, 
                      dbo.ViewProjectInquiryLostOrderDelivered.LanguageId, dbo.ViewProjectInquiryLostOrderDelivered.ResponsibleEngineerDisplayName, 
                      dbo.ViewProjectInquiryLostOrderDelivered.ResponsibleEngineerID, dbo.ViewProjectInquiryLostOrderDelivered.LostReasonCode, 
                      dbo.ViewProjectInquiryLostOrderDelivered.BranchID, dbo.ViewProjectInquiryLostOrderDelivered.BranchNameFL, 
                      dbo.ViewProjectInquiryLostOrderDelivered.BranchNameSL, dbo.ViewProjectInquiryLostOrderDelivered.CountryID, 
                      dbo.ViewProjectInquiryLostOrderDelivered.CountryName, dbo.ViewProjectInquiryLostOrderDelivered.InquiryPaymentBaseID, 
                      dbo.ViewProjectInquiryLostOrderDelivered.InquiryPriceBaseID, dbo.ViewProjectInquiryLostOrderDelivered.DeliveryTimePeriodID, 
                      dbo.ViewProjectInquiryLostOrderDelivered.OrderDeliveryTimePeriodName, dbo.ViewProjectInquiryLostOrderDelivered.FileNo
FROM         dbo.ViewProjectInquiryLostOrderDelivered LEFT OUTER JOIN
                      dbo.CompletedProjects ON dbo.ViewProjectInquiryLostOrderDelivered.ProjectSerialNumber = dbo.CompletedProjects.InquiryNumber
