CREATE VIEW [dbo].[ViewShotecProject]
AS
SELECT     dbo.ViewProjectInquiryLostOrderDeliveredCompleted.ProjectSerialNumber, dbo.ViewProjectInquiryLostOrderDeliveredCompleted.ShotecNo, 
                      dbo.ViewProjectInquiryLostOrderDeliveredCompleted.ResponsibleEngineer, dbo.ViewProjectInquiryLostOrderDeliveredCompleted.ClientName, 
                      dbo.ViewProjectInquiryLostOrderDeliveredCompleted.ClientWebsite, dbo.ViewProjectInquiryLostOrderDeliveredCompleted.ClientInquiryNumber, 
                      dbo.ViewProjectInquiryLostOrderDeliveredCompleted.InquiryDate, dbo.ViewProjectInquiryLostOrderDeliveredCompleted.ProjectStatus, 
                      dbo.ViewProjectInquiryLostOrderDeliveredCompleted.InquiryTypeID, dbo.ViewProjectInquiryLostOrderDeliveredCompleted.SupplierName, 
                      dbo.ViewProjectInquiryLostOrderDeliveredCompleted.SupplierQuotationNumber, dbo.ViewProjectInquiryLostOrderDeliveredCompleted.QuotationPrice, 
                      dbo.ViewProjectInquiryLostOrderDeliveredCompleted.QuotationCurrency, dbo.ViewProjectInquiryLostOrderDeliveredCompleted.QuotationRateToEURO, 
                      dbo.ViewProjectInquiryLostOrderDeliveredCompleted.QuotationRateDate, dbo.ViewProjectInquiryLostOrderDeliveredCompleted.QuotationPriceInEuro, 
                      dbo.ViewProjectInquiryLostOrderDeliveredCompleted.BidDueDate, dbo.ViewProjectInquiryLostOrderDeliveredCompleted.OnHold, 
                      dbo.ViewProjectInquiryLostOrderDeliveredCompleted.ModifiedDate, dbo.ViewProjectInquiryLostOrderDeliveredCompleted.UserName, 
                      dbo.ViewProjectInquiryLostOrderDeliveredCompleted.ProjectName, dbo.ViewProjectInquiryLostOrderDeliveredCompleted.ProjectLocation, 
                      dbo.ViewProjectInquiryLostOrderDeliveredCompleted.ProjectOwnerName, dbo.ViewProjectInquiryLostOrderDeliveredCompleted.ProjectDescription, 
                      dbo.ViewProjectInquiryLostOrderDeliveredCompleted.ProductName, dbo.ViewProjectInquiryLostOrderDeliveredCompleted.CategoryName, 
                      dbo.ViewProjectInquiryLostOrderDeliveredCompleted.ProductDescription, dbo.ViewProjectInquiryLostOrderDeliveredCompleted.ProjectComment, 
                      dbo.ViewProjectInquiryLostOrderDeliveredCompleted.ReasonName, dbo.ViewProjectInquiryLostOrderDeliveredCompleted.LostReasonID, 
                      dbo.ViewProjectInquiryLostOrderDeliveredCompleted.LostWinnerName, dbo.ViewProjectInquiryLostOrderDeliveredCompleted.LostWinnerPrice, 
                      dbo.ViewProjectInquiryLostOrderDeliveredCompleted.LostWinnerPriceInEuro, dbo.ViewProjectInquiryLostOrderDeliveredCompleted.LostWinnerRateToEuro, 
                      dbo.ViewProjectInquiryLostOrderDeliveredCompleted.LostWinnerRateDate, dbo.ViewProjectInquiryLostOrderDeliveredCompleted.LostWinnerPriceCurrencyID, 
                      ISNULL(dbo.ViewProjectInquiryLostOrderDeliveredCompleted.ShotecOrderNumber, '') AS ShotecOrderNumber, 
                      dbo.ViewProjectInquiryLostOrderDeliveredCompleted.CustomerOrderNumber, dbo.ViewProjectInquiryLostOrderDeliveredCompleted.SupplierOrderNumber, 
                      dbo.ViewProjectInquiryLostOrderDeliveredCompleted.DeliveryTime, dbo.ViewProjectInquiryLostOrderDeliveredCompleted.DeliveredON, 
                      dbo.ViewProjectInquiryLostOrderDeliveredCompleted.Delivered, dbo.ViewProjectInquiryLostOrderDeliveredCompleted.ExpectedDeliveryDate, 
                      dbo.ViewProjectInquiryLostOrderDeliveredCompleted.PaymentTypeID, dbo.ViewProjectInquiryLostOrderDeliveredCompleted.PriceBaseID, 
                      dbo.ViewProjectInquiryLostOrderDeliveredCompleted.OrderPrice, dbo.ViewProjectInquiryLostOrderDeliveredCompleted.OrderCurrencyID, 
                      dbo.ViewProjectInquiryLostOrderDeliveredCompleted.OrderRateToEuro, dbo.ViewProjectInquiryLostOrderDeliveredCompleted.OrderRateDate, 
                      dbo.ViewProjectInquiryLostOrderDeliveredCompleted.OrderPriceInEuro, dbo.ViewProjectInquiryLostOrderDeliveredCompleted.OrderDate, 
                      dbo.ViewProjectInquiryLostOrderDeliveredCompleted.OrderPriceCommissionBase, 
                      dbo.ViewProjectInquiryLostOrderDeliveredCompleted.OrderPercentPriceCommissionBase, dbo.Commissions.PriceCommissionBase AS CommPriceCommissionBase, 
                      dbo.Commissions.PercentPriceCommissionBase AS CommPercentPriceCommissionBase, dbo.Commissions.CommissionPercent, 
                      dbo.Commissions.CommissionAmount, dbo.Commissions.CurrencyID AS CommissionCurrencyID, dbo.Commissions.RateToEuro AS CommissionRateToEuro, 
                      dbo.Commissions.ONDate AS CommissionRateDate, dbo.Commissions.CommissionAmountInEuro, dbo.Banks.BankName, 
                      dbo.Commissions.Paid AS CommissionPaid, dbo.Commissions.MinPriceCommissionBase, dbo.Commissions.MinPercentPriceCommissionBase, 
                      dbo.Commissions.MinCommissionAmount, dbo.Commissions.MinPercentCommissionAmount, dbo.ViewProjectInquiryLostOrderDeliveredCompleted.InquiryStatus, 
                      dbo.ViewProjectInquiryLostOrderDeliveredCompleted.OrderStatus, CAST(ISNULL(dbo.view_SubViewCommissionAmounts.PaidCommissionAmount, 0) AS decimal(18, 
                      2)) AS PaidCommissionAmount, CAST(ISNULL(dbo.view_SubViewCommissionAmounts.RemainingCommissionAmount, 0) AS decimal(18, 2)) 
                      AS RemainingCommissionAmount, CAST((CASE WHEN Commissions.InquiryNumber IS NULL THEN 0 ELSE 1 END) AS Bit) AS HasCommission, 
                      dbo.ViewProjectInquiryLostOrderDeliveredCompleted.SupplierID, dbo.ViewProjectInquiryLostOrderDeliveredCompleted.LostDate, 
                      dbo.GetPrevState(dbo.ViewProjectInquiryLostOrderDeliveredCompleted.ProjectSerialNumber, dbo.ViewProjectInquiryLostOrderDeliveredCompleted.ProjectTypeID) 
                      AS PrevState, dbo.ViewProjectInquiryLostOrderDeliveredCompleted.OfferDate, dbo.ViewProjectInquiryLostOrderDeliveredCompleted.ParentInquiryNumber, 
                      dbo.ViewProjectInquiryLostOrderDeliveredCompleted.ParentOrderNumber, ISNULL(dbo.ViewProjectInquiryLostOrderDeliveredCompleted.IsSubOrder, 0) AS Expr2, 
                      dbo.ViewProjectInquiryLostOrderDeliveredCompleted.IsSubOffer, dbo.ViewProjectInquiryLostOrderDeliveredCompleted.IsSubLost, 
                      dbo.ViewProjectInquiryLostOrderDeliveredCompleted.LostParentInquiryNumber, dbo.ViewProjectInquiryLostOrderDeliveredCompleted.CustomerID, 
                      dbo.ViewProjectInquiryLostOrderDeliveredCompleted.LostComment, dbo.ViewProjectInquiryLostOrderDeliveredCompleted.ProductType, 
                      dbo.ViewProjectInquiryLostOrderDeliveredCompleted.ProductTypeID, 
                      dbo.GetInquiryOutStandingPayment(dbo.ViewProjectInquiryLostOrderDeliveredCompleted.ProjectSerialNumber) AS OutStandingPayment, 
                      dbo.ViewProjectInquiryLostOrderDeliveredCompleted.OrderPercentage, dbo.ViewProjectInquiryLostOrderDeliveredCompleted.LostPercentage, 
                      dbo.ViewProjectInquiryLostOrderDeliveredCompleted.CancelledPercentage, dbo.ViewProjectInquiryLostOrderDeliveredCompleted.LateResponsePercentage, 
                      dbo.ViewProjectInquiryLostOrderDeliveredCompleted.BackLog, dbo.ViewProjectInquiryLostOrderDeliveredCompleted.ProjectTypeID, 
                      dbo.ViewProjectInquiryLostOrderDeliveredCompleted.OrderChanceID, dbo.ViewProjectInquiryLostOrderDeliveredCompleted.OrderChance, 
                      dbo.ViewProjectInquiryLostOrderDeliveredCompleted.CompletedGoodsPaidON, dbo.ViewProjectInquiryLostOrderDeliveredCompleted.IsCompletedGoodsPaid, 
                      dbo.ViewProjectInquiryLostOrderDeliveredCompleted.HasCommission AS Expr1, dbo.ViewProjectInquiryLostOrderDeliveredCompleted.IsAllGuranteesClosed, 
                      dbo.ViewProjectInquiryLostOrderDeliveredCompleted.GuaranteesClosedDate, dbo.ViewProjectInquiryLostOrderDeliveredCompleted.IsAllCommissionPaid, 
                      dbo.ViewProjectInquiryLostOrderDeliveredCompleted.AllCommssionPaidDate, dbo.ViewProjectInquiryLostOrderDeliveredCompleted.InquiryHasGuarantee, 
                      dbo.ViewProjectInquiryLostOrderDeliveredCompleted.CompanyCode, dbo.ViewProjectInquiryLostOrderDeliveredCompleted.OrderHasGuarantee, 
                      dbo.ViewProjectInquiryLostOrderDeliveredCompleted.OrderStatusID, dbo.ViewProjectInquiryLostOrderDeliveredCompleted.ProjectID, 
                      dbo.ViewProjectInquiryLostOrderDeliveredCompleted.InquiryType, dbo.ViewProjectInquiryLostOrderDeliveredCompleted.QuotationCurrencyCode, 
                      dbo.ViewProjectInquiryLostOrderDeliveredCompleted.LostWinnerPriceCurrencyCode, dbo.ViewProjectInquiryLostOrderDeliveredCompleted.PriceBaseCode, 
                      dbo.ViewProjectInquiryLostOrderDeliveredCompleted.PaymentType, dbo.ViewProjectInquiryLostOrderDeliveredCompleted.OrderCurrencyCode, 
                      dbo.Currencies.CurrencyCode AS CommissionCurrency, dbo.Commissions.BankID, dbo.ViewProjectInquiryLostOrderDeliveredCompleted.LanguageId, 
                      dbo.ViewProjectInquiryLostOrderDeliveredCompleted.ResponsibleEngineerID, dbo.ViewProjectInquiryLostOrderDeliveredCompleted.LostReasonCode, 
                      dbo.ViewProjectInquiryLostOrderDeliveredCompleted.IsSubOrder, 
                      dbo.GetSumJobCustomerPayment(dbo.ViewProjectInquiryLostOrderDeliveredCompleted.ProjectSerialNumber) 
                      * ISNULL(dbo.ViewProjectInquiryLostOrderDeliveredCompleted.OrderPercentPriceCommissionBase, 0) * ISNULL(dbo.Commissions.CommissionPercent, 0) 
                      - dbo.GetSumJobCommissionTransactions(dbo.ViewProjectInquiryLostOrderDeliveredCompleted.ProjectSerialNumber) AS DueCommission, 
                      dbo.ViewProjectInquiryLostOrderDeliveredCompleted.BranchID, dbo.ViewProjectInquiryLostOrderDeliveredCompleted.BranchNameFL, 
                      dbo.ViewProjectInquiryLostOrderDeliveredCompleted.BranchNameSL, dbo.ViewProjectInquiryLostOrderDeliveredCompleted.CountryID, 
                      dbo.ViewProjectInquiryLostOrderDeliveredCompleted.CountryName, 
                      CASE ProjectStatus WHEN 'Inquiry' THEN '1.Inquiry' WHEN 'Offer' THEN '2.Offer' WHEN 'Order' THEN '3.Order' WHEN 'GoodsPaid' THEN '4.GoodsPaid' WHEN 'Delivered'
                       THEN '5.Delivered' END AS Ordering, dbo.ViewProjectInquiryLostOrderDeliveredCompleted.InquiryPaymentBaseID, 
                      dbo.ViewProjectInquiryLostOrderDeliveredCompleted.InquiryPriceBaseID, dbo.ViewProjectInquiryLostOrderDeliveredCompleted.DeliveryTimePeriodID, 
                      dbo.ViewProjectInquiryLostOrderDeliveredCompleted.OrderDeliveryTimePeriodName, dbo.ViewProjectInquiryLostOrderDeliveredCompleted.FileNo
FROM         dbo.Currencies INNER JOIN
                      dbo.Commissions ON dbo.Currencies.ID = dbo.Commissions.CurrencyID LEFT OUTER JOIN
                      dbo.view_SubViewCommissionAmounts ON dbo.Commissions.InquiryNumber = dbo.view_SubViewCommissionAmounts.InquiryNumber RIGHT OUTER JOIN
                      dbo.ViewProjectInquiryLostOrderDeliveredCompleted ON 
                      dbo.Commissions.InquiryNumber = dbo.ViewProjectInquiryLostOrderDeliveredCompleted.ProjectSerialNumber LEFT OUTER JOIN
                      dbo.Banks ON dbo.Commissions.BankID = dbo.Banks.ID
